repos:
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks'
    rev: v1.1.7
    hooks:
      - id: insert-license
        files: '\.[ch]$'
        args:
          - '--license-filepath=LICENSE'
          - '--comment-style=/*| *| */'
